### ISSUE TITLE
where to edit menu text of this project bro 

### ISSUE THREAD

**Issue by h1ax** [reveny/Zygisk-ImGui-Mod-Menu#4]

**Comment by h1ax** [comment]
![image](https://github.com/reveny/Zygisk-ImGui-Mod-Menu/assets/155324345/0f030c8d-80df-411e-bec2-8ec2e42f089f)
i didn't found where to edit these text. help me pls

**Comment by reveny** [comment]
https://github.com/reveny/Zygisk-ImGui-Mod-Menu/blob/443c543e88ce08a100a628a546031376c82092ad/module/src/main/cpp/modmenu.h#L47C6-L47C14

Please replace
`
ImGui::ShowDemoWindow();
`
with your own Window.
