### ISSUE TITLE
imgui window does not interact

### ISSUE THREAD

**Issue by swesws** [reveny/Zygisk-ImGui-Mod-Menu#5]
I tried to fix it. The window itself works (tested on animated text) but does not move and it is impossible to change anything. Tested on phones: Redmi Note 12 4G NFC, Samsung Galaxy A10, Samsung j4+ and more. Root: KernelSU(with zygisk module), Magisk. please fix it

**Comment by reveny** [comment]
The reason touch does not work is because you need to adjust the touch for your specific game. See
https://github.com/reveny/Zygisk-ImGui-Mod-Menu/blob/443c543e88ce08a100a628a546031376c82092ad/module/src/main/cpp/Includes/ImGui.h#L86

**Comment by swesws** [comment]
this doesn't work even in unity games.

**Comment by reveny** [comment]
> even with the unity pattern, the menu does not interact in the unity game

The pattern is different for each game. Make sure you got the correct pattern for your game
